In [1]:
#Creating Numpy Array
import numpy as np
a=np.array([1,2,3,])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2D And 3D
b= np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
a = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],

    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
#dtype
np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=bool)
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
#np arrange
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
#with  reshape
np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#np.random
np.random.random((2,3))

array([[0.92653243, 0.57911808, 0.22258216],
       [0.285154  , 0.37389115, 0.37582496]])

In [11]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attribute

In [13]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
# ndim   
a1
a2
a3.ndim

3

In [15]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [16]:
# size number of item
a3.size
a2.size

12

In [17]:
# itemsize Item occupied sized in memory
a3.itemsize
a2.itemsize
a1.itemsize

4

In [18]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## Changing Datatype

In [19]:
#astype change of datatype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operetion

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
# Scaler Opretion

# Airthmetic
a1*2
a1+2
a1-2
a1/2
a1**2
a1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [42]:
#reletional
a2>15
a2<5
a2==12
a2<=9
a2>=5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [47]:
#vector Opretion
#airthmetic
a1+a2
a1-a2
a1*a2
a1/a2


array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

## Array Function

In [61]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[38., 54., 20.],
       [88., 99., 12.],
       [73., 68., 35.]])

In [63]:
# min/max/sum/prod
# 0 ->col and 1 -> row
# np.max(a1)
# np.min(a1)
# np.prod(a1) #all elemnt multiply
np.max(a1,axis=1)
np.max(a1,axis=0)

array([88., 99., 35.])

In [71]:
# mmean/median/std/var
np.mean(a1)
np.mean(a1,axis=0)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(808.320987654321)

In [73]:
#trigonmetric function
np.sin(a1)

array([[ 0.29636858, -0.55878905,  0.91294525],
       [ 0.0353983 , -0.99920683, -0.53657292],
       [-0.67677196, -0.89792768, -0.42818267]])

In [79]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [82]:
# log and exponats
np.log(a1)

np.exp(a1)


C:\Users\ravip\AppData\Local\Temp\ipykernel_15444\3700191959.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [86]:
#  round /flor/ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[43., 29., 28.],
       [54., 59., 91.]])

## indexing Slicinng

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a1[-1]

np.int64(9)

In [5]:
a1[0]

np.int64(0)

In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a2[1,2]

np.int64(6)

In [9]:
a2[2,3]

np.int64(11)

In [10]:
a2[1,0]

np.int64(4)

In [11]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
a3[1,0,1 ]

np.int64(5)

In [14]:
a3[0,1,1]

np.int64(3)

In [15]:
a3[0,0,1]

np.int64(1)

In [16]:
a3[0,0,0]

np.int64(0)

In [17]:
a3[1,1,0]

np.int64(6)

In [19]:
#Slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a1[2:5:2]

array([2, 4])

In [23]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2[0,:]

array([0, 1, 2, 3])

In [25]:
a2[:,2]

array([ 2,  6, 10])

In [26]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [27]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [28]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [29]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [34]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [36]:
a3[0,1,:]

array([3, 4, 5])

In [37]:
a3[1,:,1]

array([10, 13, 16])

In [38]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [39]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Itererting

In [43]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [44]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [45]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [46]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

# Transpose

In [47]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [50]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Ravel

In [52]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking

In [58]:
# Horizantal Stacking
a4 = np.arange(12).reshape(3,4)
a4
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

# vertical stack

In [61]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spiting

In [63]:
# horizantal
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [68]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]